### ISSUE TITLE
Bookgen Build -a Initialize is not a valid action

### ISSUE THREAD

**Issue by Hamsterland** [webmaster442/BookGen#204]
**Describe the bug**
`Initialize` is not a valid action according to Bookgen. How can I generate a bookgen.json file?

**To Reproduce**
Run `BookGen Build -a Initialize`.

**Expected behavior**
According to the Wiki, this should create a bookgen.json file. But it does not.

**Screenshots**
![image](https://user-images.githubusercontent.com/57412787/176539099-1ad97a3b-730f-4c7b-9a0e-a9939aa91d53.png)

**System information**
 - OS: Windows
 - BookGen Build date: 2022-05-23

**Comment by webmaster442** [comment]
Sorry, the documentation is a bit outdated on the wiki. The initialize command was moved from the build actons. The correct command format is `bookgen Initialize` in the dir that you would like to create a project.

**Comment by webmaster442** [comment]
I'm currently working on the docs update and auto doc generation, so this should be fixed in the next release

**Comment by webmaster442** [comment]
I updated the wiki document with the correct command.
