### ISSUE TITLE
Cloning HttpServerFramework failed

### ISSUE THREAD

**Issue by fsebbah** [webmaster442/BookGen#205]
Cloning into 'C:/..../.....source/BookGen/HttpServerFramework'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:webmaster442/HttpServerFramework.git' into submodule path 'C:/Users/fsebb/source/BookGen/HttpServerFramework' failed
Failed to clone 'HttpServerFramework'. Retry scheduled
Cloning into 'C:/Users/fsebb/source/BookGen/HttpServerFramework'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
fatal: clone of 'git@github.com:webmaster442/HttpServerFramework.git' into submodule path 'C:/Users/fsebb/source/BookGen/HttpServerFramework' failed
Failed to clone 'HttpServerFramework' a second time, aborting

**Comment by webmaster442** [comment]
Unfortunately that's because I'm currently restructuring the code and I removed the submodules on the restructure branch. Please check that out instead of the main branch:
```bash
git clone https://github.com/webmaster442/BookGen.git
cd BookGen
git checkout Restructure
```
